project_name: mempeak

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  disable: false
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^build:'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: outofcoffee
    name: mempeak
  name_template: "{{.ProjectName}} v{{.Version}}"
  extra_files:
    - glob: ./since.yaml
  header: |
    A Unix command-line tool to monitor peak memory usage of processes and their entire process tree.
    
    ## What's Changed
  footer: |
    
    ---
    
    ## Installation
    
    Download the appropriate binary for your platform from the assets below, or use:
    
    ### Homebrew (macOS/Linux)
    ```bash
    brew install outofcoffee/tap/mempeak
    ```
    
    ### Go install
    ```bash
    go install github.com/outofcoffee/mempeak@{{.Tag}}
    ```

brews:
  - name: mempeak
    repository:
      owner: outofcoffee
      name: homebrew-tap
      token: "{{ .Env.GH_RELEASE_TOKEN }}"
    homepage: https://github.com/outofcoffee/mempeak
    description: "Monitor peak memory usage of processes, similar to 'time' but for memory"
    license: MIT
    test: |
      system "#{bin}/mempeak echo 'test'"

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://github.com/outofcoffee/mempeak
    description: Monitor peak memory usage of processes, similar to 'time' but for memory
    maintainer: outofcoffee <outofcoffee@gmail.com>
    license: MIT
    vendor: outofcoffee
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./README.md
        dst: /usr/share/doc/mempeak/README.md
      - src: ./LICENSE
        dst: /usr/share/doc/mempeak/LICENSE
    formats:
    - apk
    - deb
    - rpm
    - termux.deb
    - archlinux

